puts "Seeding database..."
# FOR TESTING PURPOSES ONLY
# PRODUCT, FOR TESTING PURPOSES ONLY
puts "1"
Product.destroy_all
product1 = Product.create({:name=>"chocolate bars", :price => 23})
product2 = Product.create({:name=>"flour", :price => 3})
product3 = Product.create({:name=>"sugar", :price => 5})
product4 = Product.create({:name=>"eggs", :price => 4})
product5 = Product.create({:name=>"milk", :price => 3})

# ORDER/LINE ORDER STUFF, FOR TESTING PURPOSES ONLY
puts "2"
puts "Total number of products: #{Product.all.count}"
puts "Product names: #{Product.all.pluck("name")}"
puts "Product1: #{product1.name} price: #{product1.price.round(2)}"
puts "Product2: #{product2.name} price: #{product2.price.round(2)}"
puts "Product3: #{product3.name} price: #{product3.price.round(2)}"
puts "Product4: #{product4.name} price: #{product4.price.round(2)}"
puts "Product5: #{product5.name} price: #{product5.price.round(2)}"

# CART, FOR TESTING PURPOSES ONLY
puts "3"
Cart.destroy_all
puts "\nTotal cart count: #{Cart.all.count}"
puts "Done seeding database."








############################################################################################################
# puts "seeding users"
# User.create!(full_name: "Adm", username: "admin", email: "admin@gmail.com", password: "admin123", user_type: "chef")
# User.create!(full_name: "Astika", username: "admin", email: "astika@gmail.com", password: "123admin", user_type: "order")
# User.create!(full_name: "mariya", username: "admin", email: "mariya@gmail.com", password: "123nbfhh", user_type: "order")


# puts "Seeding products om nom nom"
# puts "seeding breakfast products!"
# Product.create!(id: 1, name: "Eggs, Your Way", price: 5, quantity: 10, ingredients: "Eggs, Toast", allergens: "Eggs", description: "Eggs, your way. Served with white toast.", category: "Breakfast", calories: 78, image_url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.jessicagavin.com%2Fhow-to-fry-an-egg%2F&psig=AOvVaw0j1t3NDz04tCY9TjvMlPL7&ust=1668529090860000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCJjfiLCJrvsCFQAAAAAdAAAAABAN" )
# Product.create!(id: 2, name: "French Omelette", price: 8, quantity: 10, ingredients: "Eggs, Butter, Cream, Chives", allergens: "Eggs, Dairy", description: "An omelette. But an omelette like you've never had before. Its exterior is smooth as silk, its inside moist and creamy, a sheet of tender egg cradling a filling of those very same eggs, softly scrambled. Baveuse, the French say.", category: "Breakast", calories: 255, image_url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.foodnetwork.com%2Frecipes%2Ffood-network-kitchen%2Ffrench-omelet-recipe-1940898&psig=AOvVaw1PqUhN4RQpdCI7600YpmCe&ust=1668530237394000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCMij3dKNrvsCFQAAAAAdAAAAABAJ")
# Product.create!(id: 3, name: "Tamagoyaki (Rolled Japanese Omelette)", price: 8, quantity: 10, ingredients: "Eggs, Dashi, Sugar", allergens: "Eggs, Fish", description: "Tamagoyaki is Japanese rolled omelette with dashi and soy sauce, traditionally enjoyed during Japanese breakfast.", category: "Breakast", calories: 60, image_url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.justonecookbook.com%2Fjapanese-sweet-rolled-omelet%2F&psig=AOvVaw0w365UkBj12F-Fg9ckNE-7&ust=1668530300964000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCPic_fCNrvsCFQAAAAAdAAAAABAb")
# Product.create!(id: 4, name: "Waffles", price: 6, quantity: 15, ingredients: "Eggs, Flour, Milk, Oil, Sugar, Baking Powder, Salt, Vanilla", allergens: "Eggs, Dairy, Wheat", description: "Fluffy, buttery waffles, served with a side of berries.", category: "Breakast", calories: 82, image_url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.landolakes.com%2Frecipe%2F16700%2Fbelgian-style-waffles%2F&psig=AOvVaw3qkM1xg-rnyulWMkaOvSdx&ust=1668530343979000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCODRr4WOrvsCFQAAAAAdAAAAABAE")
# Product.create!(id: 5, name: "Pancakes", price: 6, quantity: 20, ingredients: "Eggs, Flour, Milk, Oil, Sugar, Baking Powder, Salt, Vanilla", allergens: "Eggs, Dairy, Wheat", description: "Fluffy, buttery pancakes, served with a side of berries.", category: "Breakast", calories: 82, image_url: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fassets.marthastewart.com%2Fstyles%2Fwmax-750%2Fd30%2Feasy-basic-pancakes-horiz-1022%2Feasy-basic-pancakes-horiz-1022_0.jpg%3Fitok%3DXQMZkp_j")
# Product.create!(id: 6, name: "French Toast", price: 7, quantity: 15, ingredients: "Eggs, Flour, Milk, Oil, Sugar, Baking Powder, Salt, Vanilla", allergens: "Eggs, Dairy, Wheat", description: "Fluffy, buttery french toast, served with a side of berries.", category: "Breakast", calories: 82, image_url: "https://d1e3z2jco40k3v.cloudfront.net/-/media/project/oneweb/mccormick-us/mccormick/recipe-images/quick_and_easy_french_toast_new_800x800.webp?rev=472bd38acf3f4e80b329915ba486cae1&vd=20220809T202043Z&hash=34381AE86E477B12B64277F710290F21")
# Product.create!(id: 7, name: "Dutch Baby (German Pancakes)", price: 7, quantity: 18, ingredients: "Eggs, Flour, Milk, Sugar, Nutmeg", allergens: "Eggs, Dairy, Wheat", description: "A large, baked pancake with a cripsy, caramelized bottom and a custardy top. Served with apples baked with brown sugar and cinnamon.", category: "Breakast", calories: 120, image_url: "https://www.jocooks.com/wp-content/uploads/2020/02/dutch-baby-pancake-1-8.jpg")
# Product.create!(id: 8, name: "Crepes (French Pancakes)", price: 7, quantity: 25, ingredients: "Eggs, Flour, Milk, Salt", allergens: "Eggs, Dairy, Wheat", description: "Thin, delicate pancakes filled with berries and rolled into a breakfast plate of delicious.", category: "Breakast", calories: 120, image_url: "https://hips.hearstapps.com/hmg-prod/images/delish-basic-crepes-horizontal-1545245797.jpg")
# Product.create!(id: 10, name: "Biscuits and Gravy", price: 8, quantity: 12, ingredients: "Flour, Baking Powder, Sugar, Milk, Pork Sausage, Eggs, Spices", allergens: "Eggs, Dairy, Wheat", description: "Just like mama made!", category: "Breakast", calories: 510, image_url: "https://carlsbadcravings.com/wp-content/uploads/2022/06/homemade-biscuits-and-gravy-recipe-11-500x375.jpg")
# Product.create!(id: 11, name: "Breakfast Casserole", price: 9, quantity: 20, ingredients: "Eggs, Pork Sausage, Heavy Cream, Green Onions, Green Bell Pepper, Red Bell Pepper, Cheddar Cheese", allergens: "Eggs, Dairy", description: "A delicious homemade breakfast casserole made with pork sausage and veggies. Freeze it and enjoy it all week!", category: "Breakast", calories: 550, image_url: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2013/6/15/0/YW0309H_Breakfast-Casserole-Trishas-Southern-Kitchen_s4x3.jpg.rend.hgtvcom.616.493.suffix/1637355586954.jpeg")
# Product.create!(id: 12, name: "Huevos Rancheros (Eggs in Salsa)", price: 12, quantity: 8, ingredients: "Black Beans, Pico de Gallo, Eggs, Corn Tortillas, Salsa, Cheese, Avocado", allergens: "Eggs, Dairy", description: "Old family recipe.", category: "Breakast", calories: 185, image_url: "https://houseofnasheats.com/wp-content/uploads/2021/05/Huevos-Rancheros-7-680x1019.jpg")
# Product.create!(id: 13, name: "Turkish Eggs", price: 11, quantity: 10, ingredients: "Eggs, Yogurt, Garlic, Lemon, Butter, Aleppo Pepper", allergens: "Eggs, Dairy", description: "Greek yogurt, whipped with lemon and garlic untl fluffy, then topped with poached eggs. browned butter, and Aleppo flakes.", category: "Breakast", calories: 473, image_url: "https://sixhungryfeet.com/wp-content/uploads/2021/02/Turkish-Eggs-2.jpg")
# Product.create!(id: 14, name: "Bauernfrühstück (Farmers Breakfast)", price: 10, quantity: 15, ingredients: "Eggs, Bacon, Potatoes, Onion, Cheese", allergens: "Eggs, Dairy", description: "A german breakfast casserole--healthy and filling!", category: "Breakast", calories: 500, image_url: "https://www.australianeggs.org.au/assets/Uploads/Bauernfruhstuck_0590__ScaleWidthWzkwMF0.jpg")
# Product.create!(id: 15, name: "Avocado Toast", price: 12, quantity: 15, ingredients: "Whole Grain Bread, Avocado, Lemon Juice, Red Pepper", allergens: "Wheat", description: "Creamy, crisp and so satisfying!", category: "Breakast", calories: 195, image_url: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2015/12/11/0/FNK_All-the-Avocado-Toast_s4x3.jpg.rend.hgtvcom.616.462.suffix/1450059496131.jpeg")
# Product.create!(id: 16, name: "Fig and Whipped Ricotta Toast", price: 12, quantity: 15, ingredients: "Whole Grain Bread, Fresh Figs, Whipped Riccota, Honey, Lemon Juice", allergens: "Wheat", description: "Creamy, sweet and so satisfying!", category: "Breakast", calories: 195, image_url: "https://pasta.com/wp-content/uploads/2021/10/Fig-Ricotta-Toast-scaled-1200x1200-cropped.jpg")
# Product.create!(id: 17, name: "Tartine au Saumon (Lox Toast)", price: 12, quantity: 15, ingredients: "Rye Caraway Bread, Smoked Salmon, Lemon Zaatar Labneh, Tomato, Pickled Onion, Everything Bagel Seasoning, Microgreens", allergens: "Wheat, Fish", description: "creamy, refreshing and so satisfying!", category: "Breakast", calories: 195, image_url: "https://recette.supertoinette.com/151716/b/tartine-a-l-avocat-et-au-saumon.jpg")
# Product.create!(id: 18, name: "Full English Breakfast", price: 12, quantity: 8, ingredients: "Bacon, Eggs, British Sausage, Baked Beans, Bubble and Squeak, Fried Tomato, Fried Mushrooms, Black Pudding, with Fried and Toasted Bread on the Side.", allergens: "Eggs, Wheat", description: "Bacon, Eggs, British Sausage, Baked Beans, Bubble and Squeak (Cooked Potatoes and Cabbage), Fried Tomato, Fried Mushrooms, Black Pudding (Traditional English Staple), with Fried and Toasted Bread on the Side.", category: "Breakast", calories: 807, image_url: "https://iamafoodblog.b-cdn.net/wp-content/uploads/2019/02/full-english-7355w-2-1024x683.jpg")
# Product.create!(id: 19, name: "Full German Breakfast", price: 11, quantity: 10, ingredients: 700, allergens: "Wheat, Dairy", description: "A German breakfast, served with hearty breads and rolls, creamy butter, sweet jams, local honey, thinly sliced meats, cheese, and Leberwurst (a type of sausage).", category: "Breakast", calories: 1200, image_url: "https://i.pinimg.com/originals/1b/b5/94/1bb594dbedb959f5ccdcd71d8dcb3a57.jpg")
# Product.create!(id: 20, name: "Lumberjack Breakfast", price: 10, quantity: 10, ingredients: "Eggs, Flour, Milk, Oil, Sugar, Baking Powder, Salt, Bacon, Sausage, Ham, Potatoes", allergens: "Eggs, Wheat", description: "The traditional American breakfast--fluffy pancakes, sausage, ham, bacon, potatoes, and two fried eggs!", category: "Breakast", calories: 910, image_url: "https://recipes.net/wp-content/uploads/2021/11/best-american-breakfast-foods.jpg")
# Product.create!(id: 21, name: "Traditional Japanese Breakfast", price: 10, quantity: 10, ingredients: "Salmon, Miso Soup, Vegetables, Rice", allergens: "Fish, Soybean", description: "Grilled salmon, steamed rice, a cup of miso soup, and some steamed veggies--very healthy!", category: "Breakast", calories: 223, image_url: "https://cdn.media.amplience.net/i/japancentre/recipes-1149-healthy-japanese-breakfast_1/Healthy-Japanese-breakfast?$poi$&w=700&h=410&sm=c&fmt=auto")
# Product.create!(id: 22, name: "Seasonal Fruit Parfait with Homemade Granola", price: 5, quantity: 8, ingredients: "Yogurt, Berries, Oats, Pecans, Almonds, Pepitas, Cinnamon, Honey, Vanilla, Dried Cranberries, Coconut Oil", allergens: "Wheat, Tree Nuts", description: "Homemade yogurt, seasonal berries, and homemade granola with locally sourced ingredients!", category: "Breakast", calories: 300, image_url: "https://feelgoodfoodie.net/wp-content/uploads/2021/05/fruit-and-yogurt-parfait-09.jpg")
# Product.create!(id: 23, name: "Lox Bagel", price: 15, quantity: 20, ingredients: "Bagel, Cream Cheese, Lox", allergens: "Wheat, Dairy, Fish", description: "Bagel with lox and homemade cream cheese of the day.", category: "Breakast", calories: 1500, image_url: "https://feelgoodfoodie.net/wp-content/uploads/2021/05/fruit-and-yogurt-parfait-09.jpg")
# Product.create!(id: 9, name: "Quiche of the Day", price: 8, quantity: 12, ingredients: "Eggs, Heavy Cream, Flour, Butter", allergens: "Eggs, Dairy", description: "A creamy daily quiche with a buttery crust and local ingredients.", category: "Breakast", calories: 600, image_url: "https://bakeitwithlove.com/wp-content/uploads/2020/09/Quiche-Lorraine-lg-sq1.jpg")
# Product.create!(id: 95, name: "Bacon, Eggs, and Cheese on a Bagel", price: 5, quantity: 6, ingredients: "Bacon, Eggs, Cheese, Bread", allergens: "Eggs, Dairy, Wheat", description: "Bacon, eggs, and cheese on a bagel.", category: "Breakast", calories: 700, image_url: "https://www.eatthis.com/wp-content/uploads/sites/4/2020/02/bacon-egg-cheese-bagel-sandwich.jpg?quality=82&strip=1")
# Product.create!(id: 96, name: "Black Bean and Avocado Breakfast Burrito", price: 5, quantity: 5, ingredients: "Eggs, Black Beans, Avocado, Salsa, Wheat Tortilla", allergens: "Eggs, Wheat", description: "Black bean and avocado breakfast burrito, served with homemade salsa.", category: "Breakast", calories: 430, image_url: "https://www.onceuponachef.com/images/2018/03/Breakfast-Burritos.jpg")
# Product.create!(id: 24, name: "Pastry Assortment", price: 8, quantity: 10, ingredients: "Flour, Sugar, Butter, Milk", allergens: "Wheat, Dairy", description: "Assortment includes cinnamon rolls, donuts, and bear claws, changes daily.", category: "Breakast", calories: 1200, image_url: "https://www.browneyedbaker.com/wp-content/uploads/2020/03/BEB-danish-pastries-36-square.jpg")
# Product.create!(id: 25, name: "Viennoiserie (Assorted French Pastry)", price: 9, quantity: 10, ingredients: "Flour, Sugar, Butter, Milk", allergens: "Wheat, Dairy", description: "Includes plain and chocolate croissants, pain aux raisins, and buttery brioche.", category: "Breakast",calories: 1650, image_url: "https://d3h1lg3ksw6i6b.cloudfront.net/media/image/2022/10/04/49c98ae8750f445c8aa266bf166d669a_frenchpastries.jpg")


# puts "seeding lunch products!"
# Product.create!(id: 26, name: "Butternut Squash Soup", price: 6, quantity: 20, ingredients: "Butternut Squash, Onion, Garlic, Tomato Paste, Mushroom Stock", allergens: "", description: "This butternut squash soup recipe is the best! Order before it runs out!", category: "Lunch, Dinner", calories: 290, image_url: "https://www.platingsandpairings.com/wp-content/uploads/2020/12/butternut-squash-bisque-7-scaled.jpg")
# Product.create!(id: 27, name: "Chicken Noodle Soup", price: 6, quantity: 20, ingredients: "Chicken, Pasta, Onions, Carrots, Celery, Parsley", allergens: "Wheat", description: "Homemade Chicken Soup--perfect for chilly winters!", category: "Lunch, Dinner", calories: 209, image_url: "https://s23209.pcdn.co/wp-content/uploads/2020/01/Homestyle-Chicken-Noodle-SoupIMG_9863.jpg")
# Product.create!(id: 28, name: "Broccoli Cheddar Soup", price: 6, quantity: 20, ingredients: "Broccoli, Cheddar Cheese, Onion, Flour, Chicken Stock, Carrots, Nutmeg", allergens: "Dairy, Wheat", description: "Better than Paneras!", category: "Lunch, Dinner", calories: 300, image_url: "https://www.halfbakedharvest.com/wp-content/uploads/2022/01/Lighter-Creamy-Broccoli-Cheddar-Soup-1.jpg")
# Product.create!(id: 29, name: "Cheeseburger Soup", price: 7, quantity: 20, ingredients: "Hamburger Meat, Cheddar Cheese, Beef Stock, Celery, Carrots, Tomatoes, Beef Stock", allergens: "Dairy", description: "Thick, hearty soup. Perfect for lunch or dinner.", category: "Lunch, Dinner", calories: 560, image_url: "https://tmbidigitalassetsazure.blob.core.windows.net/toh/GoogleImagesPostCard/Cheeseburger-Soup_EXPS_SBZ17_2832_B10_21_1b.jpg")
# Product.create!(id: 30, name: "Strawberry Soup", price: 7, quantity: 18, ingredients: "Strawberries, Coconut Milk, Sugar, Herbs", allergens: "", description: "A bright, refreshing cold soup--think gazpacho, but sweet strawberry!", category: "Lunch", calories: 192, image_url: "https://www.thedailymeal.com/sites/default/files/2016/01/26/Delaware%20-%20Strawberry%20Soup%20shutterstock.jpg")
# Product.create!(id: 31, name: "Gazpacho", price: 8, quantity: 18, ingredients: "Tomato, Cucumber, Green Bell Pepper, Red Onion, Garlic, Sherry Vinegar, Cumin, Salt and Pepper, Croutons", allergens: "Wheat", description: "Classic, refreshing, a little spicy-and very healthy!", category: "Lunch", calories: 70, image_url: "https://assets.bonappetit.com/photos/57aca0e0f1c801a1038bc671/4:3/w_2959,h_2219,c_limit/summer-gazpacho.jpg")
# Product.create!(id: 32, name: "Borscht", price: 8, quantity: 18, ingredients: "Beef Shank, Onion, Beef Stock, Beets, Carrots, Potato, Cabbage, Dill, Red Wine Vinegar", allergens: "", description: "Delicious! Order now before we sell out!", category: "Lunch", calories: 107, image_url: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Borscht_served.jpg")
# Product.create!(id: 33, name: "Nicoise Salad", price: 12, quantity: 12, ingredients: "Potatoes, Green Beans, Eggs, Shallots, Dijon Mustard, Thyme, Tomatoes, Lettuce, Radishes, Tuna", allergens: "Fish, Eggs", description: "A French salad with tuna, green beans, hard boiled eggs, tomatoes, and potatoes that's hearty enough for a main dish.", category: "Lunch, Dinner", calories: 400, image_url: "https://www.saveur.com/uploads/2019/05/21/VYIWIELVQSZVMUP5O3XVYSWBE4.jpg?auto=webp")
# Product.create!(id: 34, name: "Charlotte's Autumn Kale Salad", price: 10, quantity: 12, ingredients: "Kale, Butternut Squash, Shredded Carrots, Cheddar Cheese, Quinoa, Crispy Onions, Caramelized Onions, White Vinaigrette", allergens: "Dairy, Tree Nuts", description: "Kale, butternut squash, shredded carrots, cheddar cheese, quinoa, crispy onions, caramelized onions. Served with a white wine vinaigrette.", category: "Lunch", calories: 570, image_url: "https://www.budgetbytes.com/wp-content/uploads/2019/09/Autumn-Kale-and-Apple-Salad.jpg")
# Product.create!(id: 35, name: "Ceasar's Ceasar Salad", price: 8, quantity: 12, ingredients: "Lettuce, Parmesan Cheese, Roast Chicken, Croutons, Anchovies, Dressing.", allergens: "Fish, Dairy", description: "Made with my secret (homemade) ceasar dressing!", category: "Lunch", calories: 570, image_url: "https://www.jessicagavin.com/wp-content/uploads/2022/06/chicken-caesar-salad-28-1200.jpg")
# Product.create!(id: 36, name: "Three Bean Salad", price: 9, quantity: 13, ingredients: "Cannellini Beans, Kidney Beans, Garbanzo Beans, Celery, Red Onion, Parsley, and a Sweet and Sour Dressing", allergens: "", description: "Cannellini Beans, Kidney Beans, Garbanzo Beans, Celery, Red Onion, Parsley, and a Sweet and Sour Dressing. The perfect picnic salad!", category: "Lunch!", calories: 120, image_url: "https://cdn.loveandlemons.com/wp-content/uploads/2022/05/three-bean-salad.jpg")
# Product.create!(id: 37, name: "Strawberry Salad with Poppy Seed Dressing", price: 11, quantity: 14, ingredients: "Spinach, Strawberries, Toasted Pecans, Feta, Red Onion, Poppy Seeds, Honey, Dijon Mustard, Salt and Pepper", allergens: "Dairy, Tree Nuts", description: "A bright, refreshing salad made from sweet strawberries and a light poppy seed dressing.", category: "Lunch", calories: 120, image_url: "https://www.wellplated.com/wp-content/uploads/2019/04/Spinach-Strawberry-Salad.jpg")
# Product.create!(id: 38, name: "Goat Cheese Salad with Arugula and Apple", price: 12, quantity: 14, ingredients: "Arugula, Apples, Toasted Walnuts, Shallots, Goat Cheese, Balsamic Vinegar Dressing", allergens: "Dairy, Tree Nuts", description: "Arugula, Apples, Toasted Walnuts, Shallots, Goat Cheese, Balsamic Vinegar Dressing.", category: "Lunch", calories: 230, image_url: "https://static.onecms.io/wp-content/uploads/sites/44/2019/09/13/7104347.jpg")
# Product.create!(id: 39, name: "Roast Beef Sandwich", price: 8, quantity: 8, ingredients: "Roast Beef, Onion, Cheddar Cheese, Avocado, Mayo", allergens: "Dairy, Wheat", description: "Juicy roast beef served on thick country bread with sharp cheddar, onion, and avocado aioli.", category: "Lunch", calories: 470, image_url: "https://www.pillers.com/assets/pillers/images/hero/recipes/_2400x1000_crop_center-center_90_none/Grilled-Roast-Beef-Sandwich-Header.jpg")
# Product.create!(id: 40, name: "Chicken Salad Tartine", price: 9, quantity: 8, ingredients: "Chicken, Celery, Carrots, Cranberries, Thyme, Mayo", allergens: "Dairy, Wheat", description: "Roast chicken diced and served on thick country bread with vegetables, herbs, and cranberries.", category: "Lunch", calories: 470, image_url: "https://i.pinimg.com/736x/b7/ac/61/b7ac61d792f3b5f4cf951c8475e52b5f.jpg")
# Product.create!(id: 41, name: "Eggplant Caprese Panini", price: 7, quantity: 12, ingredients: "Eggplant, Bread Crumbs, Mozarella, Tomatoes, Basil, Olive Oil, Mayo, Sourdough.", allergens: "Dairy", description: "Thick slices of breaded eggplant served on seeded sourdough bread with smoked mozzarella, sundried tomatoes & basil aioli. Served with romesco sauce.", category: "Lunch", calories: 470, image_url: "https://www.homemadeitaliancooking.com/wp-content/uploads/2018/09/fried_eggplant_caprese_stack_closeup.jpg")
# Product.create!(id: 42, name: "Ham and Cheese Croissant", price: 7, quantity: 11, ingredients: "Ham, Cheese, Dijon, Croissant.", allergens: "Dairy, Wheat", description: "Juicy ham and gruyere cheese on a buttery, flaky croissant with a touch of dijon mustard.", category: "Lunch", calories: 320, image_url: "https://www.kitchensanctuary.com/wp-content/uploads/2016/03/Ham-and-cheese-croissants-square-500x500.jpg")
# Product.create!(id: 43, name: "Old-Fashioned Tacos", price: 12, quantity: 18, ingredients: "Beef, Onions, Cheddar, Corn Tortilla", allergens: "Dairy", description: "Ground beef ranch-style tacos with grilled onions and cheddar cheese.", category: "Lunch", calories: 470, image_url: "https://recipetineats.com/wp-content/uploads/2018/11/Beef-Tacos_2.jpg")
# Product.create!(id: 44, name: "Traditional Burrito", price: 8, quantity: 8, ingredients: "Wheat Tortilla, Black Beans, Yellow Rice, Pork, Salsa, Guacamole, Sour Cream", allergens: "Wheat, Dairy", description: "A hearty plate of beef tacos", category: "Lunch, Dinner", calories: 870, image_url: "https://www.thespruceeats.com/thmb/vequ4du_9ahBCvjuNErPtixsHsY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/vegetarian-bean-and-rice-burrito-recipe-3378550-hero-01-40ecbc08fcc84e80b8be853c1b779a13.jpg")
# Product.create!(id: 45, name: "Wades Chimichangas", price: 0, quantity: 10000, ingredients: "Love", allergens: "Dairy", description: "The best chimichangas in the city! Tell your friends!", category: "Breakfast, Lunch, Dinner", calories: 0, image_url: "https://www.cookingclassy.com/wp-content/uploads/2013/10/chicken-chimichangas-6.jpg")
# Product.create!(id: 46, name: "Fried Rice", price: 8, quantity: 8, ingredients: "Tofu, Pork, Eggs, Scallions, Onion, Carrot", allergens: "Soybeans, Eggs", description: "The ultimate comfort food!", category: "Lunch", calories: 800, image_url: "https://www.allrecipes.com/thmb/RgUS1zTYjeGmt3qW-EX9N-5GvGQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/79543-fried-rice-restaurant-style-mfs-51-155e83b4e4444e2292707287a56ddd93.jpg")
# Product.create!(id: 47, name: "Assorted Dumplings", price: 9, quantity: 20, ingredients: "Pork, Shrimp, Chicken, Mushrooms, Peas, Cabbage, Carrots, Sesame, Garlic, Soy Sauce, Flour", allergens: "Fish, Soybeans", description: "An assortment of homemade pork, shrimp, and vegetable dumplings. Served with sweet soy sauce.", category: "Lunch", calories: 750, image_url: "https://www.allrecipes.com/thmb/utcoyAc7iC0Xo2gHsHcu-sWNQQw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/14759-pork-dumplings-ddmfs-319-3x4-1-315b828b72dc47e99394915e4d539816.jpg")
# Product.create!(id: 48, name: "The Ultimate Grilled Cheese and Tomato Soup", price: 8, quantity: 8, ingredients: "Texas Toast, Cheddar, American, and Gruyere Cheese, Butter, Mayo, Tomatoes, Onion, Garlic, Chicken Stock", allergens: "Wheat, Dairy", description: "The gooeyestm meltiest, most delicious grilled cheese sandwich you will ever eat, served on thick, fluffy slices of Texas toast. Comes with a cup of homemade tomato soup for dipping!", category: "Lunch", calories: 850, image_url: "https://simply-delicious-food.com/wp-content/uploads/2019/08/Tomato-soup-with-grilled-cheese-5.jpg")
# Product.create!(id: 49, name: "Traditional Gryo", price: 12, quantity: 8, ingredients: "Pita, Lamb, Onion, Parsley, Tomato, Yogurt, Mint, Cucumber, Garlic", allergens: "Wheat, Dairy", description: "A traditional Lebanese gyro pita sandwich made with slow-cooked lamb and served with a chilled homemade mint-garlick yogurt sauce.", category: "Lunch", calories: 550, image_url: "https://www.greekboston.com/wp-content/uploads/2018/07/Traditional-Gyro.jpg")
# Product.create!(id: 50, name: "Ensalada de Nopales (Cactus Salad)", price: 12, quantity: 4, ingredients: "Grilled Cactus Leaves, Tomatoes, Green Onion, Cilantro, Cojita Cheese", allergens: "Dairy", description: "A grilled cactus salad served with a sprinkle of cojita cheese.", category: "Lunch", calories: 120, image_url: "https://mexicanfoodjournal.com/wp-content/uploads/2015/03/7-1_4.jpg")

# puts "seeding dinner products!"
# Product.create!(id: 51, name: "Margarita Pizza", price: 8, quantity: 10, ingredients: "Flour, Yeast, Sugar, Tomato Sauce, Mozzarella, Basil", allergens: "Wheat, Dairy", description: "Cheesy classic pizza.", category: "Dinner", calories: 700, image_url: "https://wgntv.com/wp-content/uploads/sites/5/2022/02/PIzzaGettyImages-852166740.jpg")
# Product.create!(id: 52, name: "Buffalo Chicken Pizza", price: 10, quantity: 10, ingredients: "Flour, Yeast, Sugar, Tomato Sauce, Mozzarella, Basil", allergens: "Wheat, Dairy", description: "Cheese classic pizza topped with buffalo chicken.", category: "Dinner", calories: 750, image_url: "https://lilluna.com/wp-content/uploads/2020/02/buffalo-chicken-pizza-resize-9.jpg")
# Product.create!(id: 53, name: "Miso Roasted Egplant", price: 10, quantity: 8, ingredients: "Eggplant, Miso, Honey, Spices", allergens: "", description: "Miso Roasted Eggplant--super healthy!", category: "Dinner", calories: 500, image_url: "https://www.justonecookbook.com/wp-content/uploads/2021/10/Miso-Glazed-Eggplants-3368-I-1.jpg")
# Product.create!(id: 54, name: "King Oyster Mushroom Steaks with Pesto and Almonds", price: 12, quantity: 10, ingredients: "King Oyster Mushrooms, Basil, Olive Oil, Garlic, Lemon, Spices, Almonds", allergens: "Almonds", description: "King Oyster Mushroom Steads with Pesto and Almonds. Vegetarian.", category: "Dinner", calories: 400, image_url: "https://www.foodandwine.com/thmb/kPh1GFFceaWSr4B0SUf7nhLvrJg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/king-oyster-mushroom-steaks-with-pesto-and-almond-aillade-FT-RECIPE0920-c48b2324178040d49fe1b4b51fb3ee18.jpg")
# Product.create!(id: 55, name: "Chicken, Feta, and Tomatoes", price: 11, quantity: 7, ingredients: "Chicken, Feta, Garlic, Cherry Tomatoes", allergens: "Dairy", description: "Roast chicken baked with feta, garlic coves, and tomatoes.", category: "Dinner", calories: 500, image_url: "https://www.servingdumplings.com/wp-content/uploads/2021/08/creamy-tomato-chicken-w-feta-1-4ab4acb3.jpg")
# Product.create!(id: 56, name: "Chicken, Grapes, and Feta", price: 11, quantity: 12, ingredients: "Chicken, Feta, Garlic, Onion Grapes", allergens: "Dairy", description: "Roast chicken baked with garlic, onion, feta, and sweet grapes.", category: "Dinner", calories: 500, image_url: "https://leitesculinaria.com/wp-content/uploads/2021/09/sheet-pan-chicken-rosemary-grapes.jpg")
# Product.create!(id: 57, name: "Chicken Pot Pie", price: 14, quantity: 11, ingredients: "Flour, Butter, Chicken, Peas, Carrots, Celery", allergens: "Wheat, Dairy", description: "Classic and hearty chicken pot pie.", category: "Dinner", calories: 800, image_url: "https://hips.hearstapps.com/hmg-prod/images/chicken-pot-pie-4-1639613061.jpg")
# Product.create!(id: 58, name: "Turkish Stuffed Eggplants", price: 12, quantity: 10, ingredients: "Eggplant, Bulgur, Onion, Garlic, Tomato Paste, Tomatoes, Vegetable Stock, Spices, Sesame, Pomegranate Seeds, Olives, Feta", allergens: "Almonds, Tree Nuts, Dairy", description: "Eggplant stuffed with bulgur and vegetables and topped with olives, feta, and pomegranate seeds.", category: "Dinner", calories: 650, image_url: "https://biancazapatka.com/wp-content/uploads/2021/10/gefuellte-auberginen.jpg")
# Product.create!(id: 59, name: "Cornbread and Sauage Casserole", price: 14, quantity: 8, ingredients: "Pork Sausage, Corn Bread, Cream Style Corn, Onion, Jalepeno Peppers, Cheddar Cheese", allergens: "Wheat, Dairy", description: "Cornbread and Sausage Casserole, for good old-fashoned southern comfort.", category: "Dinner", calories: 850, image_url: "https://www.onceuponachef.com/images/2018/11/Cornbread-Sausage-Stuffing.jpg")
# Product.create!(id: 60, name: "Roasted Butternut Squash with Goat Cheese, Pecans, and Maple Syrup", price: 12, quantity: 9, ingredients: "Butternut Squash, Goat Cheese, Pecans, Maple Syrup", allergens: "Dairy, Tree Nuts", description: "Slow-Roasted Butternut Squash topped with goat cheese, caramelized pecans, and a drizzle of maple syrup.", category: "Dinner", calories: 450, image_url: "https://eatthegains.com/wp-content/uploads/2015/12/Roasted-Butternut-Squash-8.jpg")
# Product.create!(id: 61, name: "BBQ Chicken Wings", price: 12, quantity: 12, ingredients: "Chicken Wings, BBQ Sauce", allergens: "", description: "Sticky, tangy barbeque wings. You can't go wrong with that!", category: "Dinner", calories: 750, image_url: "https://www.kitchensanctuary.com/wp-content/uploads/2020/06/bbq-chicken-wings-square-FS-8.jpg")
# Product.create!(id: 62, name: "BBQ Ribs", price: 15, quantity: 12, ingredients: "Pork Ribs, BBQ Sauce", allergens: "", description: "Sticky, tangy barbeque wings. You can't go wrong with that!", category: "Dinner", calories: 750, image_url: "https://www.onceuponachef.com/images/2022/06/baby-back-ribs-18.jpg")
# Product.create!(id: 63, name: "Skillet Macaroni and Cheese", price: 10, quantity: 8, ingredients: "Pasta, Flour, Butter, Cheese, Spices", allergens: "Wheat, Dairy", description: "A massive skillet of cheesey macaroni and cheese goodness.", category: "Dinner", calories: 1020, image_url: "https://storcpdkenticomedia.blob.core.windows.net/media/recipemanagementsystem/media/recipe-media-files/recipes/retail/x17/2020_df_retail_southern-skillet-macaroni-cheese_21107_600x600.jpg?ext=.jpg")
# Product.create!(id: 64, name: "New England Clam Chowder", price: 16, quantity: 12, ingredients: "Clams, Heavy Cream, Potatoes, Peas, Carrots, Fish Stock", allergens: "Fish", description: "Classic New England Clam Chowder served with homemade croutons.", category: "Dinner", calories: 850, image_url: "https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Contest-Winning-New-England-Clam-Chowder_EXPS_FT20_41095_F_0623_1.jpg")
# Product.create!(id: 65, name: "Maple Glazed Pork", price: 15, quantity: 10, ingredients: "Pork, Brown Sugar, Maple", allergens: "", description: "Slow-cooked maple glazed pork.", category: "Dinner", calories: 780, image_url: "https://www.5boysbaker.com/wp-content/uploads/2015/12/maple-glazed-pork-tenderloin1.jpg")
# Product.create!(id: 66, name: "Mussels with Red Curry and Coconut Rice", price: 13, quantity: 12, ingredients: "Mussels, Red Curry, Coconut Rice, Vegetables", allergens: "Fish", description: "Mussels with Red Curry and Coconut Rice", category: "Lunch, Dinner", calories: 500, image_url: "https://images.ctfassets.net/uw7yiu2kuigc/6omuJTaZypXHbTJMNGop8V/7a569ebf8a1615fbddf649963e2515e5/Red-Curry-Mussels-Lead.jpg")
# Product.create!(id: 67, name: "Yankee Pot Roast", price: 15, quantity: 10, ingredients: "Pork, Peas, Carrots, Onions, Celery, Pasta, Flour, Butter, Beef Stock", allergens: "Wheat", description: "An old-fashioned Yankee pot roast--great for the whole week!", category: "Dinner", calories: 1076, image_url: "https://cdn3.tmbi.com/toh/GoogleImagesPostCard/Traditional-Yankee-Pot-Roast_exps14021_CF2345613A06_21_4bC_RMS.jpg")
# Product.create!(id: 68, name: "Shrimp Jambalaya", price: 16, quantity: 8, ingredients: "Shrimp, Butter, Sausage, Tomatoes, Onions, Celery, Bell Peppers, Rice, Chicken Stock", allergens: "Fish", description: "Southern comfort food.", category: "Dinner", calories: 880, image_url: "https://www.dinneratthezoo.com/wp-content/uploads/2019/01/jambalaya-11.jpg")
# Product.create!(id: 69, name: "Roasted Sheet Vegetables", price: 12, quantity: 8, ingredients: "Carrots, Parsnips, Garlic, Onions, Squash, Cauliflower, Walnuts", allergens: "Tree Nuts", description: "Roasted Sheet Vegetables. An easy, healthy dinner.", category: "Dinner", calories: 250, image_url: "https://data.thefeedfeed.com/static/2020/10/07/16020980965f7e13b0ec3dd.jpg")

# puts "seeding dessert products!"
# Product.create!(id: 70, name: "Chocolate Lava Cake", price: 8, quantity: 10, ingredients: "Chocolate, Flour, Eggs, Sugar, Butter, Vanilla", allergens: "Dairy, Eggs, Wheat", description: "Rich chocolate cake with a crunchy crust and a molten lava center. A must for all chocoholics!", category: "Dessert", calories: 270, image_url: "https://www.foodnetwork.com/content/dam/images/food/fullset/2014/2/19/1/WU0701H_Molten-Chocolate-Cakes_s4x3.jpg")
# Product.create!(id: 71, name: "Chocolate Souffle", price: 9, quantity: 8, ingredients: "Chocolate, Flour, Eggs, Sugar, Butter, Vanilla", allergens: "Dairy, Eggs, Wheat", description: "The lightest, fluffiest chocolate cake you'll ever have!", category: "Dessert", calories: 300, image_url: "https://www.seriouseats.com/thmb/LfmowOJczFBnjA9DR5wlwb8kAF4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2020__10__20201003-chocolate-souffle-test2-vicky-wasik-12-e9823310c94c43498695f5c380be52cb.jpg")
# Product.create!(id: 72, name: "Apple Pie", price: 8, quantity: 10, ingredients: "Flour, Butter, Apples, Spices, Sugar", allergens: "Dairy, Wheat", description: "The perfect apple pie.", category: "Dessert", calories: 1600, image_url: "https://www.inspiredtaste.net/wp-content/uploads/2019/11/Homemade-Apple-Pie-From-Scratch-1200.jpg")
# Product.create!(id: 73, name: "Pecan Pie", price: 8, quantity: 10, ingredients: "Flour, Butter, Pecans, Spices, Sugar", allergens: "Dairy, Wheat, Tree Nuts", description: "Sweet, caramelized pecans in a soft, buttery crust. Southern cooking at its finest!", category: "Dessert", calories: 1500, image_url: "https://yestoyolks.com/wp-content/uploads/2021/11/Salted-Caramel-Pecan-Pie-4.jpg")
# Product.create!(id: 74, name: "Classic French Fruit Tart", price: 7, quantity: 12, ingredients: "Flour, Butter, Straeberries, Blueberries, Raspberries, Blackberries, Kiwi, Lemon, Sugar", allergens: "Wheat, Dairy", description: "A classic french fruit tart with fresh fruit in a flaky, buttery crust. Perfect with ice cream!", category: "Dessert", calories: 2000, image_url: "https://www.onceuponachef.com/images/2021/06/French-fruit-tart-1-scaled.jpg")
# Product.create!(id: 75, name: "Assorted Macarons", price: 9, quantity: 9, ingredients: "Eggs, Vanilla, Sugar, Almond Flour, Vailla, Natural Food Coloring, Butter, Milk, Fruit Jam", allergens: "Almonds, Dairy", description: "French macarons with a buttercream filling. Flavors include raspberry rose, caramel, and coffee.", category: "Dessert", calories: 1164, image_url: "https://sallysbakingaddiction.com/wp-content/uploads/2021/02/french-macarons.jpg")
# Product.create!(id: 76, name: "Angel Food Cake", price: 10, quantity: 8, ingredients: "Flour, Sugar, Eggs, Vanilla, Cream of Tartar", allergens: "Wheat, Eggs", description: "Light, fluffy angel food cake.", category: "Dessert", calories: 1800, image_url: "https://www.bakefromscratch.com/wp-content/uploads/2020/07/AnglefoodCake271WD4x5-696x557.jpeg")
# Product.create!(id: 77, name: "Pound Cake", price: 7, quantity: 9, ingredients: "Flour, Butter, Eggs, Sugar", allergens: "Wheat, Eggs", description: "Good with coffee.", category: "Dessert", calories: 1160, image_url: "https://www.onceuponachef.com/images/2018/01/Pound-Cake_.jpg")
# Product.create!(id: 78, name: "Olive Oil Cake", price: 8, quantity: 12, ingredients: "Flour, Sugar, Eggs, Olive Oil, Milk, Almond Extract", allergens: "Wheat, Eggs, Almonds", description: "A classic cake that pairs perfectly with fruit and a little powdered sugar.", category: "Dessert", calories: 2620, image_url: "https://cheneetoday.com/wp-content/uploads/2020/02/orange-rosemary-olive-oil-cake-1.jpg")
# Product.create!(id: 79, name: "Strawberry Cheesecake", price: 9, quantity: 10, ingredients: "Graham Crackers, Butter, Sugar, Cream Cheese, Sour Cream, Eggs, Vanilla, Strawberries", allergens: "Wheat, Dairy, Eggs", description: "Rich, creamy cheesecake topped with strawberries.", category: "Dessert", calories: 3000, image_url: "https://hips.hearstapps.com/hmg-prod/images/delish-202105-strawberrycheesecake-135-ls-1623955969.jpg?crop=1.00xw:0.752xh;0.00160xw,0.0721xh&resize=1200:*")
# Product.create!(id: 80, name: "Tiramisu", price: 9, quantity: 8, ingredients: "Flour, Sugar, Coffee, Marscapone, Heavy Cream, Marsala Wine, Rum, Lady Fingers, Cocoa Powder", allergens: "Wheat, Dairy, Eggs, Alcohol", description: "An elegant and rich layered Italian dessert made with delicate ladyfinger cookies, espresso or instant espresso, mascarpone cheese, eggs, sugar, Marsala wine, rum and cocoa powder.", category: "Dessert", calories: 2000, image_url: "https://truffle-assets.imgix.net/af88dffb-classic_tiramisu_l.jpg")
# Product.create!(id: 81, name: "Walnut Cake", price: 7, quantity: 8, ingredients: "Flour, Sugar, Eggs, Walnuts, Milk, Vanilla, Baking Powder", allergens: "Tree Nuts, Wheat, Eggs", description: "A cozy fall cake.", category: "Dessert", calories: 2152, image_url: "https://img.taste.com.au/0XhhQChH/taste/2016/11/karythopita-spiced-walnut-cake-75388-1.jpeg")
# Product.create!(id: 82, name: "Flan", price: 8, quantity: 10, ingredients: "Sugar, Eggs, Milk, Condensed Milk, Vanilla, Caramel", allergens: "Dairy, Eggs", description: "A creamy baked custard topped with caramel.", category: "Dessert", calories: 223, image_url: "https://www.cookingclassy.com/wp-content/uploads/2020/09/flan-6.jpg")
# Product.create!(id: 83, name: "Creme Brulee", price: 6, quantity: 10, ingredients: "Heavy Cream, Vanilla Bean, Sugar, Eggs", allergens: "Dairy, Eggs", description: "The classic!", category: "Dessert", calories: 286, image_url: "https://static01.nyt.com/images/2017/12/13/dining/15COOKING-CREME-BRULEE1/15COOKING-CREME-BRULEE1-master768.jpg")
# Product.create!(id: 84, name: "Assorted Cupcakes", price: 12, quantity: 20, ingredients: "Flour, Eggs, Sugar, Milk, Butter, Icing", allergens: "Wheat, Dairy, Eggs", description: "Flavors include chocolate, vanilla, and strawberry.", category: "Dessert", calories: 1572, image_url: "https://www.bakemeawish.com/images/products/pr/1000/268_1000.jpg")
# Product.create!(id: 85, name: "Ice Cream Cake", price: 15, quantity: 5, ingredients: "MIlk, Heavy Cream, Eggs, Sugar, Chocolate", allergens: "Dairy, Eggs", description: "Chocolate and vanilla ice cream cake with a cookie center.", category: "Dessert", calories: 3304, image_url: "https://i3.wp.com/lmld.org/wp-content/uploads/2021/06/Ice-Cream-Cake10.jpg")
# Product.create!(id: 86, name: "Assorted Ice Creams - Unique", price: 20, quantity: 8, ingredients: "Assorted Ice Creams - Unique", allergens: "Dairy", description: "Six pints of unique ice cream flavors, rotated frequently! Flavors might include olive oil, peach/sage, and pear/goat cheese.", category: "Dessert", calories: 4000, image_url: "https://s.hdnux.com/photos/01/25/17/72/22347441/4/1200x0.jpg")
# Product.create!(id: 87, name: "Assorted Ice Creams - Classic", price: 20, quantity: 8, ingredients: "Assorted Ice Creams - Classic", allergens: "Dairy", description: "Six pints of classic ice cream flavors, including chocolate, vanilla, caramel, and coffee.", category: "Dessert", calories: 4000, image_url: "https://www.foodbusinessnews.net/ext/resources/2022/06/27/IceCreamSurvey_Lead.jpg?t=1656349101&width=1080")
# Product.create!(id: 88, name: "Hummingbird Cake", price: 11, quantity: 7, ingredients: "Flour, Sugar, Eggs, Spices, Oil, Pineapple, Bananas, Pecans, Cream Cheese, Butter", allergens: "Wheat, Eggs, Dairy, Tree Nuts", description: "A southern classic with pineapple, banana, and pecans. It's like a tropical vacation on a plate.", category: "Dessert", calories: 3408, image_url: "https://hips.hearstapps.com/hmg-prod/images/hummingbird-cake-recipe-1646148097.jpg?crop=0.594xw:0.890xh;0.156xw,0.0663xh&resize=640:*")
# Product.create!(id: 89, name: "Coffee Cake", price: 8, quantity: 8, ingredients: "Flour, Butter, Sugar, Brown Sugar, Cinnamon, Sour Cream, Milk, Eggs, Vanilla", allergens: "Wheat, Dairy, Eggs", description: "A sweet cinnamon cake topped with sweet, crunchy struesel.", category: "Dessert", calories: 2800, image_url: "https://www.simplyrecipes.com/thmb/Alq8uC5n0EW826bqAyLGgWX5QHg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2019__04__Coffee-Cake-LEAD-1-b399ac63b52a45ac8a05b65983ab4124.jpg")
# Product.create!(id: 90, name: "Banana Bread", price: 7, quantity: 8, ingredients: "Flour, Eggs, Sugar, Milk, Bananas, Walnuts, Chocolate", allergens: "Wheat, Dairy, Tree Nuts", description: "Classic banana bread with walnuts and chocolate chips.", category: "Dessert", calories: 2000, image_url: "https://www.simplyrecipes.com/thmb/tR-5eHAZ3lgNR6Yvu3yxdHMNpk8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Easy-Banana-Bread-LEAD-2-2-63dd39af009945d58f5bf4c2ae8d6070.jpg")
# Product.create!(id: 91, name: "Banana Pudding", price: 5, quantity: 10, ingredients: "Milk, Heavy Cream, Eggs Sugar, Bananas", allergens: "Dairy", description: "Rich, creamy banana pudding.", category: "Dessert", calories: 3000, image_url: "https://www.barleyandsage.com/wp-content/uploads/2022/06/mini-banana-pudding-cups-1200x1200-1.jpg")
# Product.create!(id: 92, name: "Pot de Cremes", price: 7, quantity: 15, ingredients: "Milk, Heavy Cream, Eggs, Sugar, Chocolate", allergens: "Dairy", description: "Dark chocolate pot de cremes.", category: "Dessert", calories: 2300, image_url: "https://images-gmi-pmc.edge-generalmills.com/c2cd352b-5dba-4339-b66b-90da373f356a.jpg")
# Product.create!(id: 93, name: "Black Forest Cake", price: 12, quantity: 7, ingredients: "Flour, Sugar, Cocoa Powder, Baking Powder, Baking Soda, Eggs, Milk, Vegetable Oil, Sour Cherries, Cherry Liquor", allergens: "Wheat, Eggs, Dairy, Alcohol", description: "A German classic: layers of moist, liquor-infused chocolate cake with sweet cream and sour cherries. Delicious!", category: "Dessert", calories: 3300, image_url: "https://livforcake.com/wp-content/uploads/2017/07/black-forest-cake-thumb.jpg")
# Product.create!(id: 94, name: "Lemon Merengue Pie", price: 11, quantity: 6, ingredients: "Flour, Butter, Cream, Sugar, Eggs, Lemon Zest, Lemon Juice", allergens: "Wheat, Dairy", description: "Crisp, refreshing, and delicious!", category: "Dessert", calories: 2760, image_url: "https://dinnerthendessert.com/wp-content/uploads/2022/01/Lemon-Meringue-Pie-1x1-1.jpg")




